TOSIT-IO/tdp-collection

roles/spark/client/tasks/config.yml
roles/spark/client/tasks/install.yml
roles/spark/common/templates/pyspark-command.j2
roles/spark/common/templates/spark-shell-command.j2
roles/spark/common/templates/spark-sql-command.j2
roles/spark/common/templates/spark-submit-command.j2
roles/spark/historyserver/tasks/config.yml
tdp_vars_defaults/spark/spark.yml

Fix #225 description:
- split `spark-env.sh` vars for `spark_client` and `spark_hs` 
- configure `spark-submit`, `spark-shell` and `spark-sql` commands for direct usage

spark: configure spark commands for better usage

---

playbooks/all.yml
playbooks/exporter.yml
playbooks/exporter_jmx_install.yml
playbooks/hdfs.yml
playbooks/hdfs_jmx-exporter_config.yml
roles/exporter/jmx/tasks/install.yml
roles/hadoop/client/tasks/config.yml
roles/hadoop/common/templates/hadoop-env.sh.j2
roles/hdfs/common/templates/jmxremote.password.j2
roles/hdfs/datanode/tasks/config.yml
roles/hdfs/datanode/tasks/jmx-exporter.yml
roles/hdfs/journalnode/tasks/config.yml
roles/hdfs/journalnode/tasks/jmx-exporter.yml
roles/hdfs/namenode/tasks/config.yml
roles/hdfs/namenode/tasks/jmx-exporter.yml
roles/yarn/apptimelineserver/tasks/config.yml
roles/yarn/jobhistoryserver/tasks/config.yml
roles/yarn/nodemanager/tasks/config.yml
roles/yarn/resourcemanager/tasks/config.yml
tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/hadoop/hadoop.yml

this PR is to add jmx-exporter for **hdfs** regarding #195,  other PRs will come per service.
- add a exporter role at service level and jmx-exporter as a first component, other exporter is comming... 
- re-factoring hadoop-env.sh
- enable jmx for hdfs with authc and tls 
- add jmx-exporter for hdfs

exporter: add jmx-exporter for hdfs

---

roles/hive/client/tasks/config.yml
roles/hive/hiveserver2/tasks/config.yml
tdp_vars_defaults/hive/hive.yml
tdp_vars_defaults/hive/hive_client.yml
tdp_vars_defaults/hive/hive_hiveserver2.yml
tdp_vars_defaults/hive/hive_metastore.yml

Fix #228 description: 
- hive command can be used only by `hive` user as `hive.jceks` file was created with the following permissions : `-rw-------. 1 hive root 522 Apr 15 16:46 /etc/hive/conf/hive.jceks`
- a specific default_vars file was defined by component

hive: fix hive command usage from edge

---

roles/knox/common/templates/services/yarnui/2.7.0/rewrite.xml.j2
roles/knox/gateway/tasks/install.yml

Fixes #264 
This PR redefines the knox `rewrite.xml` of the YARNUI in order to support `https` protocol for nodemanger's links.
After this PR,  you can navigate correctly from `ResourceManger` to `NodeManager` UIs. 

knox: fix yarn nodemanager links via knox/yarnui

---

roles/knox/gateway/tasks/config.yml
roles/knox/gateway/tasks/install.yml

Fixes #268 
Depends on #265 for merge to master
Move tdp custom files from `knox_install_dir` to `knox_data_dir` in order to keep original files.

knox: move tdp custom service def from install to config

---

roles/spark/client/tasks/config.yml
roles/spark/common/templates/hive-site.xml.j2
tdp_vars_defaults/spark/spark.yml
tdp_vars_defaults/spark3/spark3.yml

Fixes #284 
Thanks to this new feature, you can use HiveSQL from different spark-clients.
e.g. : 
```
hive@mehdi-edge-01 ~]$ spark3-shell 
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2022-05-24 16:38:25,266 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Spark context Web UI available at http://mehdi-edge-01.novalocal:4040
Spark context available as 'sc' (master = yarn, app id = application_1652347047958_0126).
Spark session available as 'spark'.
Welcome to
____              __
/ __/__  ___ _____/ /__
_\ \/ _ \/ _ `/ __/  '_/
/___/ .__/\_,_/_/ /_/\_\   version 3.2.2-TDP-0.1.0-SNAPSHOT
/_/
Using Scala version 2.12.15 (OpenJDK …
```

spark: integrate hive for sql usage 

---

roles/yarn/common/templates/tmpfiles-hadoop-mapred.conf.j2
roles/yarn/jobhistoryserver/tasks/install.yml

Fixes #296 [`/run/hadoop/mapred` directory not created on boot](https://github.com/TOSIT-IO/tdp-collection/issues/296)

fix: ensure mapred pid dir persists restart

---

roles/hbase/common/tasks/install_hbase.yml

Fixes #311 
The additional level of directories in the `hbase->common->templates` dir has been accounted for here

fix: hbase tmpfiles template location

---

roles/spark/common/tasks/install.yml
roles/spark/common/templates/tmpfiles-spark.conf.j2

Fixes #309 
I parameterized the `/etc/tmpfiles.d/{{ spark_version }}.conf` filename because both Spark2 and Spark3 dual deployment would overwrite each others pid file because they both use the same variable `spark_pid_dir`.

fix:  add tmpfiles.d for spark

---

roles/hdfs/datanode/tasks/install.yml

Use default owner, group and mode for HDFS Datanode parent data dirs.
Fixes #346 

fix(hdfs): create HDFS Datanode parent data dirs

---

tdp_lib_dag/hdfs.yml
tdp_lib_dag/hive.yml
tdp_lib_dag/knox.yml
tdp_lib_dag/yarn.yml

Fixes #393 
PS : Please note that the dag was not impacted by this change 
**New restart_required Trace :**
```
2022-08-02 15:59:09,040    ranger_admin_config.yml
2022-08-02 15:59:09,041    ranger_jmx-exporter_config.yml
2022-08-02 15:59:09,041    ranger_admin_restart.yml
2022-08-02 15:59:09,041    ranger_kms_config.yml
2022-08-02 15:59:09,041    ranger_usersync_config.yml
2022-08-02 15:59:09,041    ranger_usersync_restart.yml
2022-08-02 15:59:09,041    ranger_kms_restart.yml
2022-08-02 15:59:09,042 …
```

dag: add ranger_*_config missed dependencies

---

tdp_vars_defaults/spark/spark.yml
tdp_vars_defaults/spark3/spark3.yml

Fixes #394
Fixes #395 
It appears that Spark is loading configuration from `/etc/hive/conf` by default. This is undocumented but I assume this comes from the default behavior of the HiveConf loading classes. Setting `HIVE_CONF_DIR` to the Spark conf dir allows loading the `hive-site.xml` generated for Spark.

fix(spark): specify right path for hive_conf_dir

---

roles/yarn/resourcemanager/tasks/kerberos.yml

Fixes #407 
This PR will remove Yarn dependency to HDFS by making sure that the `spnego.service.keytab` file is created on nodes where Resource Manager is installed.
----

fix(yarn): add resourcemanager spnego keytab creation

---

tdp_vars_defaults/hive/hive.yml

Delete "123" which is not consistent with Ranger Admin and Ranger KMS default database password.
Fixes #415 

feat(hive): change hive ms default database password

---

topology.ini

fix(topology): ansible group can not used bracket in topology

---

roles/ranger/admin/tasks/config.yml

Fixes #445 
The Ranger Admin install.properties file was rendered twice in a row. I removed the duplicate.
---

fix(ranger): remove install.properties task duplicate

---

playbooks/utils/ranger_policies.yml
plugins/modules/ranger_policy.py
roles/utils/ranger_policies/defaults/main.yml
roles/utils/ranger_policies/tasks/main.yml

Fixes #443 
Variable example:
```yaml
ranger_policies:
- name: tdp_user - path
description: tdp_user access to /user/tdp_user
service: hdfs-tdp
isAuditEnabled: true
isEnabled: true
resources:
path:
isExcludes: false
isRecursive: true
values: ["/user/tdp_user"]
policyItems:
- accesses:
- { isAllowed: true, type: read }
- { isAllowed: true, type: write }
- { isAllowed: true, type: execute }
conditions: []
delegateAdmin: true
groups: []
users: [tdp_user]
```
Ansible output:
```
TASK [tosit.tdp.ranger_policies : Configure Ranger Admin policies] ********************************
changed: [edge-01] => (item={'name': 'tdp_user - path', 'service': 'hdfs-tdp', 'state': 'present'})
```
Update variable (remove execute permission):
```yaml
ranger_policies:
- name: tdp_user - path
description: tdp_user …
```

feat(utils): add ranger_policies role, playbook, and module

---

roles/hbase/regionserver/tasks/config.yml
tdp_lib_dag/hbase.yml

Fixes #450 
HBase regionserver won't depend on HDFS Data Node installation anymore, and we'll get rid of 2 hard coded paths.
DAG : `hbase_regionserver_config` now depends on `hadoop_client_config`
After this, I'm finally able to install Hbase without having a local HDFS installation. 👍 
---

fix(hbase): regionserver core-site + hdfs-site from hadoop client conf

---

roles/hdfs/ranger/tasks/config.yml

fix(hdfs): hardcoded namenode config dir in hdfs ranger config

---

roles/ranger/common/templates/kms-site.xml.j2
tdp_vars_defaults/hadoop/hadoop.yml

Fixes #552
After investigation, the error is due to bad auth_to_local rules in kms-site.
This PR renders the same auth_to_local as the one in core-site. With this fix, I don't have the exception anymore.

fix(kms): render auth to local rule in kms-site

---

roles/ranger/common/templates/kms-site.xml.j2
tdp_vars_defaults/ranger/ranger_kms.yml

Fixes #564
This PR makes it possible to add properties to `kms-site.xml`.
I removed the `hadoop.kms.proxyuser.*.users` since we do template them for the hadoop core-site.

feat(ranger-kms): make kms-site additionnal properties configurable

---

tdp_vars_defaults/knox/knox.yml

Fixes #586 
I am not really happy with the result as Knox will still create the endpoint that will end up with:
But I don't see how to solve this without making the configuration super verbose with dynamic dict generation.

fix: default to empty list of hosts in topology

---

roles/knox/common/templates/knox-gateway.service.j2
tdp_vars_defaults/knox/knox.yml

Fixes #592 
I ended up removing the `javax.net.ssl.trustStore` since there was an syntax error, it was not probably useful anyway.
I also removed the `sun.debug.security.krb5.debug` property because it was spamming logs in `/var/log/knox/gateway.out`.

fix: change hardcoded knox conf dir

---

roles/hive/common/templates/hive-env.sh.j2
tdp_vars_defaults/hive/hive.yml

Fixes #638
Templating hive-env to set a default heapsize, configurable in hive's tdp_vars

fix: set hive default heapsize

---

roles/hive/metastore/tasks/config.yml
roles/utils/jceks/defaults/main.yml
roles/utils/jceks/tasks/local.yml

Fixes #180 
Here is my proposal for allowing JCEKS files update and its implementation with Hive.
The role supports using a different password than the default `none` (via the `HADOOP_CREDSTORE_PASSWORD` env var).
We can also add multiple entries to the JCEKS file with:
```
properties:
- property: key1
value: value1
- property: key2
value: value2
```

180 make hive jceks updatable

---

roles/hbase/master/tasks/ssl-tls.yml
roles/hbase/phoenix/queryserver/daemon/tasks/ssl-tls.yml
roles/hbase/regionserver/tasks/ssl-tls.yml
roles/hbase/rest/tasks/ssl-tls.yml
roles/hdfs/common/templates/httpfs-env.sh.j2
roles/hdfs/datanode/tasks/ssl-tls.yml
roles/hdfs/httpfs/tasks/ssl-tls.yml
roles/hdfs/journalnode/tasks/ssl-tls.yml
roles/hdfs/namenode/tasks/ssl-tls.yml
roles/spark/historyserver/tasks/ssl-tls.yml
roles/utils/jceks/tasks/local.yml
roles/yarn/apptimelineserver/tasks/ssl-tls.yml
roles/yarn/jobhistoryserver/tasks/ssl-tls.yml
roles/yarn/nodemanager/tasks/ssl-tls.yml
roles/yarn/resourcemanager/tasks/ssl-tls.yml
tdp_vars_defaults/hadoop/hadoop.yml
tdp_vars_defaults/hbase/hbase.yml
tdp_vars_defaults/hbase/hbase_master.yml
tdp_vars_defaults/hbase/hbase_regionserver.yml
tdp_vars_defaults/hbase/hbase_rest.yml
tdp_vars_defaults/hbase/phoenix_queryserver_daemon.yml
tdp_vars_defaults/hdfs/hdfs_datanode.yml
tdp_vars_defaults/hdfs/hdfs_httpfs.yml
tdp_vars_defaults/hdfs/hdfs_journalnode.yml
tdp_vars_defaults/hdfs/hdfs_namenode.yml
tdp_vars_defaults/spark3/spark3.yml
tdp_vars_defaults/yarn/yarn_apptimelineserver.yml
tdp_vars_defaults/yarn/yarn_mapred_jobhistoryserver.yml
tdp_vars_defaults/yarn/yarn_nodemanager.yml

Fixes #387 
Some remarks:
- `hadoop.security.credential.provider.path` is a `core-site.xml` property but I chose not to put it in the `core_site` dict since it is only copied from hadoop/client and not rendered for all services. I also think it makes more sense to put the store path in the site of the properties it holds (`ssl-server.xml` most of the time, `hbase-site.xml` for HBase REST).
- I also chose this to have a different credential store per component so we can still have different truststore / keystore files if needed.
- Hadoop HttpFs was using SSL through env vars. I switched to properties stored in `ssl-server.xml`.
- I removed the `ssl-server.xml` of HBase REST since it was useless.
- I did not implement the Hadoop credentials file in Spark 2 since our version is lacking the …

387 hadoop credential for password

---

roles/hbase/client/tasks/install.yml
roles/hbase/common/templates/hbase/hbase-env.sh.j2
tdp_vars_defaults/hbase/hbase.yml

Fixes https://github.com/TOSIT-IO/hbase/issues/2
I'm really not sure about the change I made on the variable rendering `jmx_exporter_hrs_opts`.
Context: when running `hbase hbck -j /opt/tdp/hbase/lib/hbase-hbck2-1.1.0-TDP-0.1.0-SNAPSHOT.jar`, the jar will look for the file `/etc/jmx-exporter/hrs.yml` since it reads `/etc/hbase/conf/hbase-env.sh`. Since the file is only deployed on RS and not the edge, this raises an error.
The fix is to remove the declaration of this file during the rendering of `hbase-env.sh` when running on an edge.
I think it can cause issues if a node is a RS and a edge as it would render the hbase-env.sh without the JMX exporter. I don't know if  that's a real issue. I'm doing some more tests to see if renders the file correctly for RS but I'm open to suggestions to …

 feat: add hbck2 jar on hbase client install 

---

tdp_vars_defaults/spark/spark.yml
tdp_vars_defaults/spark3/spark3.yml

This PR fixes the error when lauching a sparksql session via livy
`evalue": "java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf when creating Hive client using classpath: \nPlease make sure that jars for your version of hive and hadoop are included in the paths passed to spark.sql.hive.metastore.jars`

fix(spark): integration of sparksql and livy

---

roles/yarn/resourcemanager/tasks/install.yml

Fixes #727 
This PR fixes the error that can intervene when starting Yarn Node Manager :
```
Caused by: ExitCodeException exitCode=24: File /etc/hadoop/conf.rm must be owned by root, but is owned by 1019
```
This configuration folder was the only one not owned by root.

fix(yarn rm): rm conf dir owned by root

---

roles/hadoop/common/templates/hadoop-env.sh.j2
tdp_vars_defaults/hadoop/hadoop.yml

Fixes #751 
Docs on this : https://effectivemachines.com/2016/08/06/adding-to-apache-hadoops-classpath/
- Java classes can be added to the classpath programatically
- Some modules are available in `hadoop/hadoop-tools` including 
- hadoop-aws
- hadoop-azure
- ...
- One can enable these modules (= adding them to the classpath) with the HADOOP_OPTIONAL_TOOLS env
- In my case I just add hadoop-aws to this variable
- It then enables the shellprofile hadoop-aws (located in `/opt/tdp/hadoop/libexec/shellprofile.d/hadoop-aws.sh`
- This shellprofile add hadoop-aws to the classpath

feat: render HADOOP_OPTIONAL_TOOLS

---

tdp_vars_defaults/hbase/hbase_client.yml

Fixes #757  
When using hbase client binaries (hbase shell)
- the HBASE_ROOT_LOGGER env (in `hbase-env.sh`) is set `INFO,RFA` in every hbase module.
- This environment variable is translated and added to HBASE_OPTS in `/opt/tdp/hbase/bin/hbase`
```
HBASE_OPTS="$HBASE_OPTS -Dhbase.root.logger=${HBASE_ROOT_LOGGER:-INFO,console}"
```
- Since the RFA is a RollingFileAppender, log4j tries to write to `/var/log/hbase/hbase.log`
- Using `hbase shell`, the user is not necessarily root nor hbase as it's available on a edge node
- A "Permission Denied" is thrown and shown to the user even though it's just a logging error.
Setting 'console' instead of RFA for hbase_client fixes the issue. Logs are shown directly on the hbase shell (default INFO, which is not very verbose)

fix: use console appender instead of RFA for hbase client

---

roles/zookeeper/common/tasks/install.yml

Fixes #754 
By removing the `recurse: true` when ensuring `"{{ hadoop_root_dir }}/{{ zookeeper_dist_release }}"` permissions are correct, ZooKeeper instances will still be able to serve requests as the permissions on `{{ hadoop_root_dir }}/{{ zookeeper_dist_release }}/zkData` and underlying paths will remain untouched (`zookeeper:hadoop`) even if `tosit.tdp.meta.zookeeper` is run multiple times.
I made some tests and did not find any regression after removing the `recurse: true`.

fix(zk): do not apply zookeeper install directory permissions recursively

---

roles/hbase/ranger/tasks/config.yml
roles/hdfs/ranger/tasks/config.yml
roles/hive/ranger/tasks/config.yml
roles/knox/ranger/tasks/config.yml
roles/ranger/admin/tasks/config.yml
roles/ranger/kms/tasks/config.yml
roles/ranger/usersync/tasks/config.yml
roles/yarn/ranger/tasks/config.yml

Fixes #776
I kept the "export JAVA_HOME" during each script to keep existing feature. Maybe it is not useful anymore as JAVE_HOME should be defined in globab env var.

776 Remove hardcoded JAVA_HOME in the roles/

---

tdp_vars_defaults/hadoop/hadoop.yml
tdp_vars_defaults/spark3/spark3.yml

Give hue user  access to yarn and spark application log

feat(hue): enable application log on jobbrowser of hue

---

.ansible-lint
.github/workflows/ansible-lint.yml
plugins/modules/resolve.py

fix: ansible-lint can't load module tosit.tdp.resolve

---

roles/spark/client/tasks/install.yml
roles/spark/common/tasks/install.yml
roles/spark/common/templates/sparkr-shell-command.j2
tdp_vars_defaults/spark/spark.yml
tdp_vars_defaults/spark3/spark3.yml

This PR allows the ability to use R langage on Spark. SparkR can be launched with the command: sparkr3-shell
Fixes #764 
To integrate SparkR :
- Installation of R ;
- symbolic link from the sparkr folder to R library ;
- render /usr/bin/sparkr-shell command.
Requires :
New build of spakr3.2 with sparkR profile activated is required. 
To build spark3.2 with sparkR, follow guideline in README.md file of R. Make sure that your build environment have R > 3.5.

feat(sparkR): integration of sparkr

---

tdp_vars_defaults/yarn/yarn.yml

Fixes #809
disable vmem-check for better jupyterhub integration.
As described in[ this hadoop documentation](https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/NodeManagerCGroupsMemory.html), this check can be useful in case of Elastic Memory Control.

yarn: disable vmem-check for better jupyterhub integration

---

roles/knox/common/templates/services/livy3/0.4.3/rewrite.xml.j2
roles/knox/common/templates/services/livy3/0.4.3/service.xml.j2
roles/knox/gateway/tasks/config.yml
tdp_vars_defaults/knox/knox.yml

Fixes #813
- livy with spark2 link : https://<knox_host>/gateway/tdpldap/livy
- livy with spark3 link : https://<knox_host>/gateway/tdpldap/livy3

knox: add support of two instances of livy with spark2 (livy) and spark3 (livy3)

---

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

Timestamp for hours was coded 'hh' which is hours in am/pm format (0-12)
Loki needs hours from 0 to 23

fix: timestamp formatting in logs from 12h to 24h

---

roles/hadoop/client/tasks/config.yml
roles/hbase/client/tasks/config.yml
roles/hbase/master/tasks/config.yml
roles/hbase/phoenix/queryserver/client/tasks/config.yml
roles/hbase/phoenix/queryserver/daemon/tasks/config.yml
roles/hbase/regionserver/tasks/config.yml
roles/hbase/rest/tasks/config.yml
roles/hdfs/datanode/tasks/config.yml
roles/hdfs/httpfs/tasks/config.yml
roles/hdfs/journalnode/tasks/config.yml
roles/hdfs/namenode/tasks/config.yml
roles/hive/client/tasks/config.yml
roles/hive/hiveserver2/tasks/config.yml
roles/hive/metastore/tasks/config.yml
roles/knox/gateway/tasks/config.yml
roles/spark/client/tasks/config.yml
roles/spark/historyserver/tasks/config.yml
roles/yarn/apptimelineserver/tasks/config.yml
roles/yarn/jobhistoryserver/tasks/config.yml
roles/yarn/nodemanager/tasks/config.yml
roles/yarn/resourcemanager/tasks/config.yml
roles/zookeeper/client/tasks/config.yml
roles/zookeeper/server/tasks/config.yml

Fixes #824
backup tasks will now be launched by using the following syntax :
~~~
ansible-playbook <playbook.yml> --tags all,backup
~~~

fix: run backup task only when specified

---

roles/hive/common/templates/hive-env.sh.j2

fix: Remove log4j v1 jars from hive CLASSPATH

---

roles/hdfs/ranger/tasks/config.yml
roles/yarn/ranger/tasks/config.yml

Ranger plugin config for hdfs and yarn breaks the symbolic link that was previously created by [hadoop client installation](https://github.com/TOSIT-IO/tdp-collection/blob/2784de6f9df0d40e4713d8026cb7b8fd1a932b47/roles/hadoop/client/tasks/install.yml#L23).
This fix recreates the link back to its original value, after the enable plugin script has run.

fix: reestablish hadoop conf link

---

roles/hive/metastore/tasks/install.yml
roles/ranger/admin/tasks/install.yml
roles/ranger/kms/tasks/install.yml
tdp_vars_defaults/hive/hive.yml
tdp_vars_defaults/ranger/ranger.yml

Fixes #861
Works with PR [tdp-collection-prerequisites#103](https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/103) which must be merged before. The JDBC connector installation is performed in the prerequisites now and not in tdp-collection anymore.

fix: mysql-connector-java install

---

tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/hadoop/hadoop.yml
tdp_vars_defaults/hbase/hbase.yml
tdp_vars_defaults/hive/hive.yml
tdp_vars_defaults/knox/knox.yml
tdp_vars_defaults/ranger/ranger.yml
tdp_vars_defaults/spark/spark.yml
tdp_vars_defaults/spark3/spark3.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
tdp_vars_defaults/zookeeper/zookeeper.yml

feat: globalize root_dir variables

---

playbooks/utils/decommissioning/README.md
playbooks/utils/decommissioning/excluded_nodes.yml
playbooks/utils/decommissioning/hadoop-component-decommissioning-check.yml
playbooks/utils/decommissioning/hadoop-components-decommissioning/hdfs_namenode_decomm_datanode.yml
playbooks/utils/decommissioning/hadoop-components-decommissioning/yarn_resourcemanager_decomm_nodemanager.yml
playbooks/utils/decommissioning/hadoop-decommissioning.yml
roles/hdfs/namenode/tasks/config.yml
roles/utils/hadoop_decommissioning_check/tasks/main.yml
roles/utils/hdfs_namenode_decommissioning/defaults/main.yml
roles/utils/hdfs_namenode_decommissioning/tasks/main.yml
roles/utils/hdfs_namenode_decommissioning/templates/dfs.exclude.j2
roles/utils/yarn_resourcemanager_decommissioning/defaults/main.yml
roles/utils/yarn_resourcemanager_decommissioning/tasks/main.yml
roles/utils/yarn_resourcemanager_decommissioning/templates/yarn.exclude.j2
roles/yarn/resourcemanager/tasks/config.yml
tdp_vars_defaults/hdfs/hdfs.yml
tdp_vars_defaults/yarn/yarn.yml

Fixes None
Added decommission playbooks and roles for yarn and HDFS to decommission a worker node.

feat: decommission playbooks

---

tdp_vars_defaults/hive/hive.yml

Set postgres backend as default for hive metastore

feat: set postgres as default for metastore

---

roles/spark/README.md
tdp_vars_defaults/spark3/spark3.yml

Fixes None
Changed spark3 version to `3.2.4-1.0` in `tdp_vars_default`

feat: changed spark3 version

---

tdp_vars_defaults/hadoop/hadoop.yml
tdp_vars_defaults/hbase/hbase.yml
tdp_vars_defaults/hive/hive.yml
tdp_vars_defaults/knox/knox.yml

Set latest component versions

---

tdp_vars_defaults/hbase/hbase.yml
tdp_vars_defaults/knox/knox.yml

Hello, 
Please could you merge this PR, it fixes the #893 issue.
Regards

feat(tdp_vars_defaults): changes in order tu use phoenix via knox

---

roles/hadoop/common/templates/hadoop-env.sh.j2
roles/hbase/common/templates/hbase/hbase-env.sh.j2
roles/hbase/common/templates/phoenix_queryserver/hbase-env.sh.j2
roles/hdfs/common/templates/hadoop-env.sh.j2
roles/hdfs/common/templates/httpfs-env.sh.j2
roles/hive/common/templates/hive-env.sh.j2
roles/yarn/common/templates/hadoop-env.sh.j2
tdp_vars_defaults/hadoop/hadoop.yml
tdp_vars_defaults/hbase/hbase.yml
tdp_vars_defaults/hdfs/hdfs.yml
tdp_vars_defaults/hive/hive.yml
tdp_vars_defaults/yarn/yarn.yml

Partially fixes #898 
In order to add garbage collect configuration to hadoop daemon (required in #898), it is needed to add custom *_OPTS to daemon e.g: `-XX:PermSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=4000 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70` need to be added to HADOOP_NAMENODE_OPTS.
The PR adds to templates hadoop-env.sh, hbase-env.sh and hive-env.sh a way to add arbitrary JVM opts to the hadoop client, HDFS client, namenode, datanode, journalnode, YARN resourcemanager, nodemanager, timelineserver, mapred historyserver, HIVE client, hiveserver2 and metastore.

Add arbitrary OPTS to env.sh

---

roles/ranger/common/templates/usersync_install.properties.j2

ranger-usersync: fix variable rangerUsersync_password hardcoded

---

tdp_vars_defaults/knox/knox.yml

Fixes no issue created.
livy server spark2 and spark3 are hard coded.
It was done this way since variables comes from tdp_collection_extras and can be undefined. I added a logic to manage undefined variables. it is not perfect but it fixes the issue of managing undefined variable.

fix(knox): livy servers port are hardcoded

---

tdp_vars_defaults/knox/knox.yml

One can not expect livyserver haprovider to work out of the box at the moment. There are multiple issues regarding session, recovery of sessinn and HA for session.
It is preferable to remove livyserver HAProvider to remove confusion.
Also this change is coherent with not accepting #904

fix: remove livyserver haprovider

---

tdp_vars_defaults/spark3/spark3.yml

Fixes PR  [spark3: enable dynamic allocation #909](https://github.com/TOSIT-IO/tdp-collection/pull/909) 
Variabilize the spark-version in `spark_yarn_shuffle_path`.

fix(spark3): variabilize spark version for yarn shuffle

---

roles/hive/common/tasks/hdfs_init.yml
roles/spark/common/tasks/hdfs_init.yml
roles/yarn/common/tasks/hdfs_init.yml

Fixes #931
Use sticky permissions `1777` instead of `777` for HDFS folders.

refactor(permissions): change all folder 777 permissions to 1777 in hdfs

---

roles/zookeeper/common/tasks/install.yml

Fixes [Zookeeper issue ](https://github.com/TOSIT-IO/zookeeper/issues/1)
This sets all folders and files with permissions `755`. [With `follow: false`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-follow) files related to symlinks do not change permissions. By default, for ansible < 2.5 it is false (we currently use version 2.15), but for versions superior to 2.5 it is set by default to true.

fix(zookeeper): give 755 permissions to all folders

---

roles/spark/common/templates/log4j2.properties.j2
roles/spark/historyserver/tasks/config.yml
tdp_vars_defaults/spark3/spark3.yml

Fixes #927
Use log4j2 configuration. RFA and DRFA do not rollover but the same with configuration in spark2 which uses log4j1.

fix(spark): use log4j2 log configuration

---

roles/hbase/common/tasks/install_hbase.yml
roles/hbase/common/tasks/install_phoenix.yml
roles/hbase/phoenix/queryserver/common/tasks/install.yml
roles/hbase/ranger/tasks/install.yml
roles/hdfs/namenode/tasks/start_standby_nn.yml
roles/hdfs/ranger/tasks/install.yml
roles/hive/common/tasks/install_hive.yml
roles/hive/ranger/tasks/install.yml
roles/knox/common/tasks/install.yml
roles/knox/ranger/tasks/install.yml
roles/ranger/admin/tasks/config.yml
roles/yarn/nodemanager/tasks/install.yml
roles/yarn/ranger/tasks/install.yml

Fixes None
As stated in #940 with [`follow: false`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-follow) files related to symlinks do not change permissions. By default, for ansible < 2.5 it is false (we currently use version 2.15), but for versions superior to 2.5 it is set by default to true.

refactor: add follow=false for recurse option in ansible

---

topology.ini

hdfs: add ha to Httpfs ha

---

tdp_vars_defaults/ranger/ranger.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

Fixes the following error in `hdfs_ranger_init` when variable is not overriden 
```
The task includes an option with an undefined variable. The error was: 'ranger_admin_password' is undefined. 
```

fix: Move ranger_admin_password to tdp_cluster
