playbooks/yarn_apptimelineserver_restart.yml, playbooks/yarn_mapred_jobhistoryserver_restart.yml, playbooks/yarn_nodemanager_restart.yml, roles/yarn/apptimelineserver/tasks/restart.yml, roles/yarn/jobhistoryserver/tasks/restart.yml, roles/yarn/nodemanager/tasks/restart.yml
=> yarn: add restart

playbooks/exporter_jmx_install.yml, playbooks/yarn.yml, playbooks/yarn_jmx-exporter_config.yml, roles/hadoop/common/templates/hadoop-env.sh.j2, roles/yarn/apptimelineserver/tasks/config.yml, roles/yarn/apptimelineserver/tasks/jmx-exporter.yml, roles/yarn/common/templates/jmxremote.password.j2, roles/yarn/jobhistoryserver/tasks/config.yml, roles/yarn/jobhistoryserver/tasks/jmx-exporter.yml, roles/yarn/nodemanager/tasks/config.yml, roles/yarn/nodemanager/tasks/jmx-exporter.yml, roles/yarn/resourcemanager/tasks/config.yml, roles/yarn/resourcemanager/tasks/jmx-exporter.yml, tdp_vars_defaults/hadoop/hadoop.yml
=> exporter: add jmx-exporter for yarn

roles/hdfs/namenode/tasks/formatzk.yml
=> hdfs: add fail condition to formatzk

playbooks/hdfs.yml
=> hdfs: reorder hdfs_jmx-exporter_config playbook

playbooks/hbase_phoenix_queryserver_daemon_restart.yml, playbooks/hbase_rest_restart.yml, playbooks/restart_all.yml, playbooks/restart_hbase.yml, playbooks/restart_hdfs.yml, playbooks/restart_yarn.yml, roles/hbase/phoenix/queryserver/daemon/tasks/restart.yml, roles/hbase/rest/tasks/restart.yml
=> all: refacto restart

playbooks/zookeeper.yml, playbooks/zookeeper_jmx-exporter_config.yml, roles/zookeeper/common/templates/jmxremote.password.j2, roles/zookeeper/common/templates/zookeeper-env.sh.j2, roles/zookeeper/server/tasks/config.yml, roles/zookeeper/server/tasks/jmx-exporter.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> exporter: add jmx-exporter for zookeeper

.gitignore, playbooks/spark3.yml, playbooks/spark3_client_config.yml, playbooks/spark3_client_install.yml, playbooks/spark3_hdfs_init.yml, playbooks/spark3_historyserver_config.yml, playbooks/spark3_historyserver_install.yml, playbooks/spark3_historyserver_restart.yml, playbooks/spark3_historyserver_start.yml, playbooks/spark3_historyserver_stop.yml, playbooks/spark3_kerberos_install.yml, playbooks/spark3_ssl-tls_install.yml, roles/spark/README.md, roles/spark/client/tasks/config.yml, roles/spark/client/tasks/install.yml, roles/spark/common/tasks/hdfs_init.yml, roles/spark/common/templates/spark-history-server.service.j2, roles/spark/historyserver/tasks/install.yml, roles/spark/historyserver/tasks/restart.yml, roles/spark/historyserver/tasks/start.yml, roles/spark/historyserver/tasks/stop.yml, tdp_lib_dag/spark3.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/spark3/spark3.yml
=> feat: add spark3

playbooks/all.yml
=> fix(spark3): import spark3 playbook in all.yml

tdp_vars_defaults/hdfs/hdfs.yml
=> feat(hdfs): remove dfs.replication overwritting

roles/knox/common/templates/services/spark3historyui/3.0.0/rewrite.xml.j2, roles/knox/gateway/tasks/config.yml
Fixes #290 by resolving yarn urls for containers' logs.
=> knox: integrate Spark3 history server UI

roles/hive/common/tasks/install_hive.yml, roles/hive/common/templates/tmpfiles-hive-server2.conf.j2
Fixes #298
Additional PRs incoming for the other components affected by this issue
=> fix: add tmpfiles.d for hive-server2

roles/hbase/common/tasks/install_hbase.yml, roles/hbase/common/templates/hbase/tmpfiles-hbase.conf.j2
=> fix: add tmpfiles.d for hbase

roles/exporter/node/tasks/install.yml, roles/exporter/node/templates/tmpfiles-node-exporter.conf.j2
=> fix: add tmpfiles.d for node-exporter

roles/knox/common/tasks/install.yml, roles/knox/common/templates/tmpfiles-knox.conf.j2
=> fix: add tmpfiles.d for knox

tdp_lib_dag/knox.yml
=> dag: init ranger plugin before knox-gateway start

tdp_vars_defaults/spark3/spark3.yml
=> feat(spark3): enforce pyspark python version

roles/ranger/admin/tasks/install.yml, roles/ranger/common/templates/tmpfiles-ranger-usersync.conf.j2, roles/ranger/common/templates/tmpfiles-ranger.conf.j2, roles/ranger/usersync/tasks/install.yml
=> 307 ranger tmpfiles fix

tdp_vars_defaults/hadoop/hadoop.yml
=> feat: add mapred am client port range to defaults

tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> 324 spark port range parameters

roles/knox/common/templates/topology.xml.j2
- Add 'applications' as a list of strings possibility in topology
- Add 'parameters' for services in topology
Fixes #328 
=> feat(knox): add parameters to knox topology templates

tdp_lib_dag/hive.yml
=> fix(dag): init ranger plugin for hive before hiveserver2 start

roles/zookeeper/client/tasks/config.yml, roles/zookeeper/client/tasks/install.yml, roles/zookeeper/client/tasks/kerberos.yml, roles/zookeeper/common/tasks/install.yml, roles/zookeeper/common/templates/jaas.client.conf.j2, roles/zookeeper/common/templates/java.env.client.j2, roles/zookeeper/common/templates/java.env.j2, roles/zookeeper/common/templates/java.env.server.j2, roles/zookeeper/common/templates/log4j.properties.j2, roles/zookeeper/common/templates/zookeeper-env.sh.j2, roles/zookeeper/common/templates/zookeeper.service.j2, roles/zookeeper/server/tasks/config.yml, roles/zookeeper/server/tasks/install.yml, roles/zookeeper/server/tasks/kerberos.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> feat(zookeeper): move zookeeper config to /etc

roles/hdfs/datanode/tasks/install.yml
=> feat(hdfs): handle multiple data dir for HDFS Datanode data dir

roles/hive/common/tasks/init_schema.yml
=> hive: use hive logs for schema validation

tdp_vars_defaults/hive/hive_hiveserver2.yml
=> disable hs2 http-cookie-auth for better integration with knox

roles/zookeeper/check/tasks/main.yml, roles/zookeeper/client/tasks/install.yml, roles/zookeeper/common/templates/zoo.cfg.j2, roles/zookeeper/common/templates/zookeeper.service.j2, roles/zookeeper/server/tasks/install.yml, roles/zookeeper/server/tasks/jmx-exporter.yml, roles/zookeeper/server/tasks/restart.yml, roles/zookeeper/server/tasks/start.yml, roles/zookeeper/server/tasks/stop.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> refactor(zookeeper): prepare for multiple versions

.gitattributes
=> refactor(github): add yaml to language statistics

roles/spark/client/tasks/config.yml
=> fix(spark3): make hbase dependency deployment optional

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hdfs/hdfs.yml
=> fix(kms): resolve kms property in the core-site.xml

roles/spark/client/tasks/config.yml, roles/spark/client/tasks/install.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> fix(spark): add spark_hbase_connector_enable for optional deployment

tdp_vars_defaults/hdfs/hdfs.yml
=> fix(kms): fix dfs.encryption.key.provider.uri for optional kms usage

roles/ranger/common/templates/usersync_install.properties.j2, tdp_vars_defaults/ranger/ranger.yml
=> feat(ranger): fill usersync_install.properties

playbooks/meta/all.yml, playbooks/meta/hbase.yml, tdp_lib_dag/hbase.yml
=> fix(dag): add ranger plugin dependency to hbase_master_start

tdp_lib_dag/hdfs.yml, tdp_lib_dag/knox.yml, tdp_lib_dag/ranger.yml, tdp_lib_dag/spark.yml, tdp_lib_dag/spark3.yml
Fixes #381 
`restart_required` trace after `hadoop.yml` change :
```
2022-07-28 12:18:29,195  hadoop_client_config.yml
2022-07-28 12:18:29,195  ranger_admin_config.yml
2022-07-28 12:18:29,196  ranger_admin_restart.yml
2022-07-28 12:18:29,196  ranger_kms_config.yml
2022-07-28 12:18:29,196  ranger_usersync_restart.yml
2022-07-28 12:18:29,196  ranger_kms_init.yml
2022-07-28 12:18:29,196  ranger_kms_restart.yml
2022-07-28 12:18:29,196  hdfs_datanode_config.yml
2022-07-28 12:18:29,197  hdfs_namenode_config.yml
2022-07-28 …
```
=> fix(dag): add hadoop_client_config missed dependencies

tdp_lib_dag/hbase.yml, tdp_lib_dag/hdfs.yml, tdp_lib_dag/ranger.yml
Fixes #381 
`restart_required` trace after `hadoop.yml` change:
```
2022-07-29 11:21:58,965      hadoop_client_config.yml
2022-07-29 11:21:58,966      ranger_admin_config.yml
2022-07-29 11:21:58,967      ranger_admin_restart.yml
2022-07-29 11:21:58,967      ranger_kms_config.yml
2022-07-29 11:21:58,967      ranger_usersync_config.yml
2022-07-29 11:21:58,967      ranger_usersync_restart.yml
2022-07-29 11:21:58,968      ranger_kms_init.yml
2022-07-29 11:21:58,968      ranger_kms_restart.yml
2022-07-29 11:21:58,968 …
```
=> fix(dag): add hadoop_client_config missed dependencies (2)

roles/exporter/node/templates/node-exporter.service.j2, roles/hbase/common/templates/hbase/hbase-master.service.j2, roles/hbase/common/templates/hbase/hbase-regionserver.service.j2, roles/hbase/common/templates/hbase/hbase-rest.service.j2, roles/hbase/common/templates/phoenix_queryserver/phoenix-queryserver.service.j2, roles/hdfs/common/templates/hadoop-hdfs-datanode.service.j2, roles/hdfs/common/templates/hadoop-hdfs-journalnode.service.j2, roles/hdfs/common/templates/hadoop-hdfs-namenode.service.j2, roles/hdfs/common/templates/hadoop-hdfs-zkfc.service.j2, roles/hive/common/templates/hive-metastore.service.j2, roles/hive/common/templates/hive-server2.service.j2, roles/knox/common/templates/knox-gateway.service.j2, roles/ranger/common/templates/ranger-admin.service.j2, roles/ranger/common/templates/ranger-kms.service.j2, roles/ranger/common/templates/ranger-usersync.service.j2, roles/ranger/common/templates/solr_standalone/solr.service.j2, roles/spark/common/templates/spark-history-server.service.j2, roles/yarn/common/templates/hadoop-mapred-jobhistoryserver.service.j2, roles/yarn/common/templates/hadoop-yarn-nodemanager.service.j2, roles/yarn/common/templates/hadoop-yarn-resourcemanager.service.j2, roles/yarn/common/templates/hadoop-yarn-timelineserver.service.j2, roles/zookeeper/common/templates/zookeeper.service.j2
Fixes #384 
From my tests, adding `After=` and `Wants=` requirements is enough for all the services to start without trouble on reboot.
=> feat: add systemd services requirements

tdp_vars_defaults/hive/hive.yml
=> feat(hive): secure hiveserver2 web ui

roles/utils/ssl_tls/defaults/main.yml, roles/utils/ssl_tls/tasks/convert_cert_key.yml, roles/utils/ssl_tls/tasks/create_keystore.yml, roles/utils/ssl_tls/tasks/create_truststore.yml, roles/utils/ssl_tls/tasks/verify_truststore.yml
=> feat(ssl): set permissions on certs/stores

tdp_vars_defaults/spark3/spark3.yml
=> fix(spark3): add execution engine to hive-site.xml

tdp_vars_defaults/spark/spark.yml
=> fix(spark2): add execution engine to hive-site.xml

roles/ranger/usersync/tasks/config.yml, roles/ranger/usersync/tasks/install.yml, tdp_vars_defaults/ranger/ranger.yml
=> fix(ranger): define python interpreter for ranger-usersync setup.py

roles/hive/metastore/tasks/kerberos.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> feat(hive): remove hive_ms specific principal

roles/yarn/apptimelineserver/tasks/kerberos.yml, roles/yarn/jobhistoryserver/tasks/kerberos.yml
Fixes #409 
Installation of `apptimelineserver` and `jobhistoryserver` yarn components won't rely on other components prior installation regarding SPNEGO keytab creation anymore.
---
=> fix(yarn): add ats and jhs spnego keytab creation

roles/yarn/apptimelineserver/tasks/kerberos.yml
=> fix: correct yml syntax

README.md
Use Github contributors list.
Fixes #417 
=> feat(readme): remove contributors

tdp_vars_defaults/all/all.yml
=> bootstrap tdp_vars_defaults all.yml service/component ports

playbooks/utils/hdfs_user_homes.yml, roles/utils/hdfs_user_homes/defaults/main.yml, roles/utils/hdfs_user_homes/tasks/main.yml
=> feat(utils): add hdfs_user_homes role and playbook

roles/hadoop/common/templates/core-site.xml.j2, tdp_vars_defaults/hadoop/hadoop.yml
=> feat: make auth_to_local rules mergeable between collections

roles/ranger/admin/tasks/hdfs.yml
=> fix(ranger): resolve hdfs dependency via hdfs-site symbolic link 

plugins/action/resolve.py
Fixes #469 
YAML tested:
```yaml
number: 2
hello_{{ number }}: key_should_be_hello_2
test_site:
var1: false
var_{{ number }}: key_should_be_var_2
test_{{ test_site['var1'] }}: key_should_be_test_False
value_should_be_2: "{{ number }}"
test_{{ number }}: "value_{{ number }}"
```
Result:
```json
{
"number": 2,
"hello_2": "key_should_be_hello_2",
"test_site": {
"var1": false,
"var_2": "key_should_be_var_2",
"test_False": "key_should_be_test_False",
"value_should_be_2": 2,
"test_2": "value_2"
}
}
```
Edge case that we choose not to support:
```yaml
number: 2
test_site:
test_{{ test_site['test_' + (number | string)] }}: key_should_be_test_value_2
test_{{ number }}: "value_{{ number }}"
```
This the case we want to template a key depending on another templated key.
To make clear that you …
=> feat: make resolve able to template keys

playbooks/meta/all.yml, playbooks/meta/all_per_service.yml, playbooks/meta/hive.yml, tdp_lib_dag/hive.yml, tdp_lib_dag/spark.yml, tdp_lib_dag/spark3.yml
Fixes #475
```
2022-10-04 09:21:01,125     hive_client_config.yml
2022-10-04 09:21:01,125     hbase_client_config.yml
2022-10-04 09:21:01,125     hive_hiveserver2_config.yml
2022-10-04 09:21:01,125     hive_ranger_config.yml
2022-10-04 09:21:01,126     hive_hiveserver2_restart.yml
2022-10-04 09:21:01,126     hbase_jmx-exporter_config.yml
2022-10-04 09:21:01,126     hbase_master_config.yml
2022-10-04 09:21:01,126     hbase_phoenix_queryserver_client_config.yml
2022-10-04 09:21:01,127 …
```
=> fix(dag): add hbase dependencies with hiveserver2 and Spark2/3

tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/knox/knox.yml
=> fix(hdfs): rafactor ports usage

tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/yarn/yarn.yml
=> yarn: refactor ports usage

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/yarn/yarn.yml
=> fix(mapred): refactor ports usage

tdp_lib_dag/hbase.yml
=> fix(dag): yarn_client_config as hbase_client_config dependency

playbooks/hdfs_namenode_check.yml, roles/hdfs/namenode/tasks/check.yml, tdp_vars_defaults/hdfs/hdfs.yml
=> hdfs: namenode component check

tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> hive: refactor ports usage

playbooks/meta/all.yml, playbooks/meta/ranger.yml, playbooks/ranger_solr_init.yml, playbooks/ranger_solr_install.yml, playbooks/ranger_solr_restart.yml, playbooks/ranger_solr_start.yml, roles/ranger/common/templates/solr_standalone/solr.service.j2, roles/ranger/common/templates/solr_standalone/tmpfiles-solr.conf.j2, roles/ranger/solr/tasks/install.yml, tdp_lib_dag/ranger.yml
=> Fix Solr install

tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> spark2|3: refactor ports usage

tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> hbase: refactor ports usage

tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> phoenix: refactor ports usage

roles/ranger/common/templates/install.properties.j2, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> knox: refactor ports usage

tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> fix(hdfs): rename + add missing datanode ports

roles/hbase/master/tasks/restart.yml
=> fix: rename hbase master restart duplicate key

.github/PULL_REQUEST_TEMPLATE.md
PR made with the template:
Fixes #520
=> fix: markdown syntax

playbooks/hdfs_datanode_check.yml, roles/hdfs/datanode/tasks/check.yml, tdp_vars_defaults/hdfs/hdfs.yml
=> hdfs: add datanode component check

roles/hdfs/namenode/tasks/check.yml, roles/zookeeper/check/tasks/main.yml, roles/zookeeper/server/tasks/check.yml
Fixes #524
Add fixes to Zookeeper server & service checks and to HDFS namenode component check.
=> Fix all service checks return ok status

playbooks/hdfs_ranger_check.yml, roles/hdfs/ranger/tasks/check.yml, tdp_vars_defaults/hdfs/hdfs.yml
=> hdfs: add ranger plugin component check

playbooks/hdfs_check.yml, roles/hdfs/check/tasks/main.yml, tdp_vars_defaults/hdfs/hdfs.yml
=> hdfs: add service check

roles/exporter/node/templates/node-exporter.service.j2, roles/ranger/common/templates/ranger-kms.j2, tdp_vars_defaults/exporter/exporter.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> exporter: refactor ports usage

playbooks/hbase_kerberos_install.yml
=> fix: set hbase_kerberos_install's client target as hbase_client

tdp_vars_defaults/yarn/yarn.yml
=> fix(yarn): use dominant resource calculator

playbooks/zookeeper_check.yml, playbooks/zookeeper_server_check.yml
Fixes #529
This will fix:
- the environment variable LC_ALL: C is missing
- node_name values are not correct
=> Fix zookeeper issues in server/service check playbooks

roles/spark/client/tasks/config.yml, roles/spark/client/tasks/install.yml
=> spark2: add hbase_client check before hbase-spark-connector install

playbooks/meta/all.yml, playbooks/meta/spark.yml, playbooks/meta/spark3.yml, playbooks/spark3_jmx-exporter_config.yml, playbooks/spark_jmx-exporter_config.yml, roles/spark/common/templates/jmxremote.password.j2, roles/spark/historyserver/tasks/config.yml, roles/spark/historyserver/tasks/jmx-exporter.yml, tdp_lib_dag/spark.yml, tdp_lib_dag/spark3.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> spark2|3: add exporter for history servers

roles/zookeeper/server/tasks/install.yml
=> fix: renamed var zookeeper_data_dir

roles/hadoop/common/templates/hadoop-env.sh.j2, tdp_vars_defaults/hdfs/hdfs.yml
=> hdfs: add resources allocation management

tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> fix: add hbase_install_dir variable

roles/hadoop/common/templates/hadoop-env.sh.j2, roles/hdfs/common/templates/hadoop-env.sh.j2, roles/yarn/common/templates/hadoop-env.sh.j2
=> hadoop: fix vars dependecies after hdfs resources allocation

tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Fixes `None`
This PR adds the HDFS ZKFC port to the configuration.
=> feat: add missing zkfc port to hdfs_site

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/yarn/yarn.yml
Fixes `None`
This PR adds a bunch of missing ports for YARN and MapReduce components.
=> feat: add missing yarn + mapred ports to tdp_vars

tdp_vars_defaults/spark/spark.yml
=> fix(spark): fix jxm exporter config for spark_hs

roles/knox/common/templates/services/yarnui/2.7.0/rewrite.xml.j2
=> fix(knox): resolve spark3 urls from yarn-ui

roles/hdfs/check/tasks/main.yml
=> fix: use hdfs_headless_principal for kinit

roles/yarn/common/templates/hadoop-env.sh.j2, roles/yarn/common/templates/krb5JAASrm.conf.j2, roles/yarn/resourcemanager/tasks/kerberos.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/yarn/yarn.yml
=> feat: create YARN znode with secure ACLs

tdp_vars_defaults/hadoop/hadoop.yml
=> feat(mapreduce): add resources allocation management

roles/yarn/common/templates/hadoop-env.sh.j2, tdp_vars_defaults/yarn/yarn.yml
=> yarn: add resources allocation management

roles/ranger/common/templates/kms-site.xml.j2
Fixes #599 
See [kms-site.xml.j2](https://github.com/TOSIT-IO/tdp-collection/blob/97844b2ce1804f1d1b84f08b5898616606cc4f25/roles/ranger/common/templates/kms-site.xml.j2) at 97844b2ce1804f1d1b84f08b5898616606cc4f25 for reference.
=> fix: close for loop in kms-site template

roles/hive/client/tasks/config.yml, roles/hive/metastore/tasks/config.yml, roles/knox/gateway/tasks/config.yml
=> fix: quote passwords in creds stores ops

tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> feat(spark2|3): add resources allocation management

roles/ranger/common/templates/ranger-admin-services.sh.j2, roles/ranger/common/templates/ranger-kms.j2, roles/ranger/common/templates/ranger-usersync-services.sh.j2, roles/ranger/common/templates/solr_standalone/solr.service.j2, roles/ranger/solr/tasks/install.yml, tdp_vars_defaults/ranger/ranger.yml
=> ranger: add resources allocation management

roles/knox/common/templates/gateway.sh.j2, tdp_vars_defaults/knox/knox.yml
=> knox: add resources allocation management

dev/requirements.txt, dev/validate_schema.py, tdp_vars_schema/hadoop.json, tdp_vars_schema/hdfs.json
Fixes #606
This PR bootstraps schema description and validation implementation.
=> feat: implement schema description and validation

tdp_lib_dag/exporter.yml
=> fix: add tdp-cluster dependency to exporter components

playbooks/exporter_jmx_install.yml, playbooks/hdfs_httpfs_config.yml, playbooks/hdfs_httpfs_install.yml, playbooks/hdfs_httpfs_restart.yml, playbooks/hdfs_httpfs_start.yml, playbooks/hdfs_httpfs_stop.yml, playbooks/hdfs_jmx-exporter_config.yml, playbooks/hdfs_kerberos_install.yml, playbooks/hdfs_ssl-tls_install.yml, playbooks/meta/hdfs.yml, roles/hdfs/common/templates/hadoop-hdfs-httpfs.service.j2, roles/hdfs/common/templates/httpfs-env.sh.j2, roles/hdfs/common/templates/httpfs-site.xml.j2, roles/hdfs/httpfs/tasks/config.yml, roles/hdfs/httpfs/tasks/install.yml, roles/hdfs/httpfs/tasks/jmx-exporter.yml, roles/hdfs/httpfs/tasks/kerberos.yml, roles/hdfs/httpfs/tasks/restart.yml, roles/hdfs/httpfs/tasks/ssl-tls.yml, roles/hdfs/httpfs/tasks/start.yml, roles/hdfs/httpfs/tasks/stop.yml, roles/hdfs/httpfs/templates, tdp_lib_dag/hdfs.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hdfs/hdfs_httpfs.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, topology.ini
=> hadoop: add httpfs

roles/yarn/common/templates/tmpfiles-hadoop-yarn.conf.j2, roles/yarn/nodemanager/tasks/install.yml, tdp_vars_defaults/yarn/yarn.yml
=> yarn: add cgroups feature for better dynamic resources management

roles/zookeeper/common/tasks/install.yml
=> fix: check permissions after extract

roles/hbase/common/templates/hbase/hbase-env.sh.j2, tdp_vars_defaults/hbase/hbase.yml
=> hbase: add resources allocation management

roles/hive/common/templates/hive-env.sh.j2, tdp_vars_defaults/hive/hive.yml
=> hive: add resources allocation management

roles/hbase/common/templates/phoenix_queryserver/hbase-env.sh.j2, tdp_vars_defaults/hbase/hbase.yml
=> phoenix: add resources allocation management

playbooks/hdfs_audit_init.yml, playbooks/meta/all.yml, playbooks/meta/hdfs.yml, roles/hdfs/common/tasks/hdfs_audit_init.yml, tdp_lib_dag/hdfs.yml
=> feat: add hdfs audit log dir creation

roles/zookeeper/common/templates/log4j.properties.j2, tdp_vars_defaults/zookeeper/zookeeper.yml
Fixes #640 
- add a daily rolling file appender `DFRA`
- add a rolling file appender by size `RFA`
- only `DRFA` or `RFA` and not both must be used at the same time
- make layout pattern configurable via a tdp var in order to unify it with other logs and make easier the integration of a log management tool 
- remove unused vars from tdp vars
=> feat(zookeeper): unify log4j configuration for better log management

roles/zookeeper/common/templates/log4j.properties.j2, tdp_vars_defaults/zookeeper/zookeeper.yml
Fixes #640 
- define naming rule for log files that will be applied for the other components
=> fix(zookeeper): format logs files name

roles/knox/gateway/tasks/config.yml, roles/knox/gateway/tasks/ssl-tls.yml, tdp_vars_defaults/knox/knox.yml
=> feat: use generic keystore/truststore for knox

playbooks/meta/all.yml
=> fix: regenerate meta all

roles/ranger/common/templates/ranger-admin-services.sh.j2, roles/ranger/common/templates/ranger-kms.j2, roles/ranger/common/templates/ranger-usersync-services.sh.j2
Fixes #647 
I moved the `JMX_OPTS` vars to start actions of the scripts for each service.
=> fix(ranger): move JMX_OPTS var to start actions

roles/spark/common/templates/spark-history-server.service.j2
=> fix(spark): add SuccessExitStatus=143 to HS service

tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> fix(spark): correct resources properties names

roles/utils/jceks/tasks/local.yml
=> fix: correct path variable

playbooks/hbase_phoenix_ssl-tls_install.yml, playbooks/hbase_ssl-tls_install.yml, playbooks/hdfs_ssl-tls_install.yml, playbooks/hive_ssl-tls_install.yml, playbooks/knox_ssl-tls_install.yml, playbooks/ranger_ssl-tls_install.yml, playbooks/spark3_ssl-tls_install.yml, playbooks/spark_ssl-tls_install.yml, playbooks/yarn_ssl-tls_install.yml
=> fix: correct node_name in the ssl-tls playbooks

playbooks/yarn_mapred_jobhistoryserver_config.yml, playbooks/yarn_mapred_jobhistoryserver_install.yml, playbooks/yarn_mapred_jobhistoryserver_restart.yml, playbooks/yarn_mapred_jobhistoryserver_start.yml, playbooks/yarn_mapred_jobhistoryserver_status.yml, playbooks/yarn_mapred_jobhistoryserver_stop.yml, playbooks/yarn_ssl-tls_install.yml
=> fix: node_name in yarn_ssl-tls

playbooks/hdfs_audit_init.yml
=> fix: fix mitogen strategy for hdfs_audit_init playbook

tdp_vars_defaults/firewall/firewall.yml
=> YARN firewall rules

roles/firewall/firewalld/tasks/config.yml, tdp_vars_defaults/firewall/firewall.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> Hive firewall rules

roles/hbase/phoenix/queryserver/common/tasks/install.yml
=> fix(phoenix): resolve phoenix binaries' permessions

plugins/inventory/tdp_vars.py
=> feat: load tdp variables from collections defaults

playbooks/firewall_generic_start.yml, roles/firewall/generic/tasks/config.yml, roles/firewall/generic/tasks/restart.yml, roles/firewall/generic/tasks/start.yml, tdp_vars_defaults/firewall/firewall.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Depends on:
- #567 
- #655 
- #658 
=> HBase firewall rules

roles/hadoop/client/tasks/config.yml, roles/hadoop/common/templates/log4j.properties.j2, roles/hdfs/common/tasks/install.yml, roles/hdfs/common/templates/hadoop-env.sh.j2, roles/hdfs/common/templates/httpfs-env.sh.j2, roles/hdfs/common/templates/install_hdfs.properties.j2, roles/hdfs/datanode/tasks/config.yml, roles/hdfs/httpfs/tasks/config.yml, roles/hdfs/journalnode/tasks/config.yml, roles/hdfs/namenode/tasks/config.yml, roles/yarn/apptimelineserver/tasks/config.yml, roles/yarn/common/tasks/install.yml, roles/yarn/common/templates/hadoop-env.sh.j2, roles/yarn/common/templates/install_yarn.properties.j2, roles/yarn/jobhistoryserver/tasks/config.yml, roles/yarn/jobhistoryserver/tasks/install.yml, roles/yarn/nodemanager/tasks/config.yml, roles/yarn/resourcemanager/tasks/config.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hadoop/hadoop_client.yml, tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/yarn/yarn.yml, tdp_vars_defaults/yarn/yarn_jobhistoryserver.yml
=> Unify log4j configuration for better log management for all hadoop components

roles/ranger/common/templates/install.properties.j2, tdp_vars_defaults/firewall/firewall.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Depends on:
- #567 
- #655 
- #658 
- #659 
=> Spark + Knox firewall rules

tdp_vars_defaults/firewall/firewall.yml
Depends on:
- #567 
- #655 
- #658 
- #659 
- #664 
=> Exporters firewall rules

tdp_vars_defaults/yarn/yarn_jobhistoryserver.yml, tdp_vars_defaults/yarn/yarn_mapred_jobhistoryserver.yml
Fixes #695 in order to resolve a vars' confilct for `yarn_mapred_jobhistoryserver` created by #680 and #681
=> fix(yarn): resolve mapred vars' bug

roles/hbase/common/templates/hbase/hbase-env.sh.j2, roles/hbase/common/templates/hbase/install_hbase.properties.j2, roles/hbase/common/templates/hbase/log4j.properties.j2, tdp_vars_defaults/hbase/hbase.yml
=> hbase: unify log4j configuration for better log management

roles/hbase/common/templates/phoenix_queryserver/hbase-env.sh.j2, roles/hbase/common/templates/phoenix_queryserver/log4j.properties.j2, roles/hbase/phoenix/queryserver/daemon/tasks/config.yml, roles/hbase/phoenix/queryserver/daemon/tasks/install.yml, tdp_vars_defaults/hbase/hbase.yml
=> phoenix: unify log4j configuration for better log management

roles/knox/common/templates/gateway-log4j.properties.j2, roles/knox/common/templates/gateway.sh.j2, roles/knox/common/templates/install.properties.j2, tdp_vars_defaults/knox/knox.yml
=> feat(knox): unify log4j configuration for better log management

playbooks/utils/tdp_ports.yml, roles/ranger/common/templates/install.properties.j2, tdp_vars_defaults/firewall/firewall.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Depends on:
- #665 
This PR enriches firewall rules short names and descriptions. This enables the automatic generation of a Markdown documentation (in a table or list format) of all the TDP ports by running the `utils/tdp_ports` playbook.
```sh
ansible-playbook ansible_collections/tosit/tdp/playbooks/utils/tdp_ports.yml -e 'format=table'
```
=> 422 firewall ports doc

topology.ini
Section include ranger_admin, ranger_kms and hive_ms
Fixes https://github.com/TOSIT-IO/tdp-collection-prerequisites/issues/67
Relates to PR https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/68
=> refactor: add postgresql_client section

roles/ranger/admin/tasks/config.yml, roles/ranger/admin/tasks/install.yml, roles/ranger/common/templates/kms_install.properties.j2, roles/ranger/common/templates/log4j.properties.j2, roles/ranger/common/templates/ranger-admin-services.sh.j2, roles/ranger/common/templates/ranger-kms.j2, roles/ranger/common/templates/ranger-usersync-services.sh.j2, roles/ranger/common/templates/solr_standalone/log4j2.properties.j2, roles/ranger/common/templates/solr_standalone/solr.service.j2, roles/ranger/kms/tasks/config.yml, roles/ranger/kms/tasks/install.yml, roles/ranger/solr/tasks/install.yml, roles/ranger/usersync/tasks/config.yml, roles/ranger/usersync/tasks/install.yml, tdp_vars_defaults/ranger/ranger.yml
=> ranger: unify log4j configuration for better log management hive 

roles/spark/common/templates/log4j.properties.j2, roles/spark/historyserver/tasks/config.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> spark 2|3 : unify log4j configuration for better log management

roles/hbase/common/templates/hbase/hbase-env.sh.j2, roles/hbase/common/templates/phoenix_queryserver/hbase-env.sh.j2, roles/hdfs/common/templates/hadoop-env.sh.j2, roles/hdfs/common/templates/httpfs-env.sh.j2, roles/knox/common/templates/gateway-log4j.properties.j2, roles/ranger/common/templates/usersync_install.properties.j2, roles/yarn/common/templates/hadoop-env.sh.j2, roles/zookeeper/common/templates/log4j.properties.j2, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> log4j: refactor log vars after log management integration

plugins/inventory/tdp_vars.py
"tdp_vars" inventory plugin need a "tdp_collection" option or environment variable "TDP_COLLECTION_PATH". When this option or environment variable is not defined warnings are displayed and are not understandable.
This commit add an understandable warning message.
Moreover the inventory plugin no longer throws an exception to prevent other inventory plugins from launching.
Fixes #708 
Before:
```
[WARNING]:  * Failed to parse .../inventory/tdp_vars.yaml with auto plugin: No setting was provided for required configuration plugin_type: inventory plugin:
ansible_collections.tosit.tdp.plugins.inventory.tdp_vars setting: tdp_collection
[WARNING]:  * Failed to parse .../inventory/tdp_vars.yaml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse …
```
=> chore(plugins): display an understandable message if an option is missing

roles/hive/common/templates/hive-env.sh.j2, roles/hive/common/templates/hive-log4j2.properties.j2, roles/hive/common/templates/install.properties.j2, tdp_vars_defaults/hive/hive.yml
=> hive: unify log4j configuration for better log management

roles/hbase/master/tasks/hdfs_init.yml
=> fix(hbase): create hdfs directory for hbase

roles/spark/common/tasks/hdfs_init.yml
=> fix(spark): create hdfs directory for spark

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/yarn/yarn.yml, tdp_vars_defaults/yarn/yarn_mapred_jobhistoryserver.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=>  Prepare tdp-collection integration with tdp-observability

roles/hdfs/ranger/tasks/check.yml, roles/ranger/common/templates/install.properties.j2, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, topology.ini
Fixes #699
As discussed in [#59](https://github.com/orgs/TOSIT-IO/discussions/59) and announced in [#100](https://github.com/TOSIT-IO/tdp-collection-extras/issues/100#issuecomment-1428048876), this PR implements configuration changes that were developed in `422-all-firewall-rules`.
Other changes from that branch are implemented in `tdp-collection-extras` via [#103](https://github.com/TOSIT-IO/tdp-collection-extras/pull/103)
=> feat: update port variables

tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> ldap: centralize ldap vars in tdp_cluster

roles/ranger/common/templates/ranger-ugsync-site.xml.j2, roles/ranger/usersync/tasks/config.yml, tdp_vars_defaults/ranger/ranger_usersync.yml
=> 657 usersync template

roles/ranger/admin/tasks/config.yml, roles/ranger/admin/tasks/kerberos.yml, roles/ranger/common/templates/install.properties.j2, roles/utils/ranger_policies/tasks/main.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/yarn/yarn.yml, topology.ini
=> feat(ranger): add ha support for ranger admin

topology.ini
=> feat(ranger): add ranger usersync ha

roles/exporter/node/tasks/install.yml, roles/hadoop/common/tasks/install.yml, roles/hbase/common/tasks/install_hbase.yml, roles/hbase/common/tasks/install_phoenix.yml, roles/hbase/phoenix/queryserver/common/tasks/install.yml, roles/hbase/ranger/tasks/install.yml, roles/hdfs/ranger/tasks/install.yml, roles/hive/common/tasks/hdfs_init.yml, roles/hive/common/tasks/install_hive.yml, roles/hive/ranger/tasks/install.yml, roles/knox/common/tasks/install.yml, roles/knox/ranger/tasks/install.yml, roles/ranger/admin/tasks/install.yml, roles/ranger/kms/tasks/install.yml, roles/ranger/solr/tasks/install.yml, roles/ranger/usersync/tasks/install.yml, roles/spark/common/tasks/install.yml, roles/yarn/ranger/tasks/install.yml, roles/zookeeper/common/tasks/install.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> Variabilize the /tmp path for uploaded files

roles/ranger/admin/tasks/kerberos.yml
=> fix(ranger): fix kerberos block checks for optional deployment

.gitignore, roles/exporter/jmx/tasks/install.yml, roles/exporter/node/tasks/install.yml, roles/hadoop/common/tasks/install.yml, roles/hbase/client/tasks/install.yml, roles/hbase/common/tasks/install_hbase.yml, roles/hbase/common/tasks/install_phoenix.yml, roles/hbase/phoenix/queryserver/common/tasks/install.yml, roles/hbase/ranger/tasks/install.yml, roles/hdfs/ranger/tasks/install.yml, roles/hive/common/tasks/hdfs_init.yml, roles/hive/common/tasks/install_hive.yml, roles/hive/ranger/tasks/install.yml, roles/knox/common/tasks/install.yml, roles/knox/ranger/tasks/install.yml, roles/ranger/admin/tasks/install.yml, roles/ranger/kms/tasks/install.yml, roles/ranger/solr/tasks/install.yml, roles/ranger/usersync/tasks/install.yml, roles/spark/client/tasks/install.yml, roles/spark/common/tasks/install.yml, roles/yarn/ranger/tasks/install.yml, roles/zookeeper/common/tasks/install.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat: add binaries_local_dir variable for local binaries directory

roles/hdfs/check/tasks/main.yml, roles/hdfs/datanode/tasks/check.yml, roles/hdfs/journalnode/tasks/check.yml, roles/hdfs/namenode/tasks/check.yml, roles/zookeeper/check/tasks/main.yml, roles/zookeeper/server/tasks/check.yml
=> Fix to remove ansible.builtin. from service & component check files

roles/knox/gateway/tasks/config.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> 656 clear knox password

tdp_vars_defaults/ranger/ranger_kms.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> fix(ranger): move kms logs to specific dir

tdp_vars_defaults/knox/knox.yml
=> knox: remove ranger-ui from topology

topology.ini
=> exporter_node: remove groups from topology.ini

playbooks/hbase_hdfs_init.yml, playbooks/hdfs_audit_init.yml, playbooks/hdfs_check.yml, playbooks/hdfs_kerberos_install.yml, playbooks/hive_hdfs_init.yml, playbooks/hive_kerberos_install.yml, playbooks/knox_hdfs_init.yml, playbooks/spark3_hdfs_init.yml, playbooks/spark3_kerberos_install.yml, playbooks/spark_hdfs_init.yml, playbooks/spark_kerberos_install.yml, playbooks/utils/hdfs_user_homes.yml, playbooks/yarn_hdfs_init.yml, playbooks/yarn_kerberos_install.yml, playbooks/zookeeper_kerberos_install.yml
=> fix: update playbooks with componants client groups

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hdfs/hdfs.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/yarn/yarn.yml
Fixes #760 
Still as draft due to spark not being release yet
=> 760 Use TDP 1.0 releases files

roles/knox/common/templates/services/yarnui/2.7.0/rewrite.xml.j2
=> knox: enable apps' kill from yarn-ui

roles/hbase/ranger/tasks/config.yml, roles/hdfs/namenode/tasks/start_standby_nn.yml, roles/hive/common/tasks/hdfs_init.yml, roles/hive/common/templates/hive-env.sh.j2, roles/hive/ranger/tasks/config.yml, roles/knox/ranger/tasks/config.yml, roles/knox/ranger/tasks/init.yml, roles/utils/jceks/defaults/main.yml, roles/utils/jceks/tasks/local.yml
=> 768 some opttdp path are not variabilize

tdp_vars_defaults/knox/knox.yml
Fixes #784 and depends on this extra PR [##139](https://github.com/TOSIT-IO/tdp-collection-extras/pull/139/)
=> knox: livy integration with HA mode

playbooks/wait_sleep.yml
=> feat(playbooks): add playbook to wait (useful for tdp-lib)

tdp_vars_defaults/spark/spark.yml
=> spark: fix python version

tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/hbase/hbase.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/ranger/ranger.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/zookeeper/zookeeper.yml
=> fix: enforce ISO8601 standard on log timestamps

tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
=> spark: set yarn cluster mode by default for better resiliency

tdp_vars_defaults/knox/knox.yml
=> Add support for knox topology customization

roles/spark/common/templates/pyspark-command.j2, roles/spark/common/templates/spark-shell-command.j2, roles/spark/common/templates/spark-sql-command.j2, roles/spark/common/templates/sparkr-shell-command.j2
=> Spark2|3: fix spark shell after setting yarn cluster mode by default

roles/knox/common/templates/services/livy/0.4.3/rewrite.xml.j2, roles/knox/common/templates/services/livy/0.4.3/service.xml.j2, roles/knox/gateway/tasks/config.yml
=> knox: fix broken yarn links for livy

roles/knox/common/templates/services/webhdfs/2.4.0/rewrite.xml.j2, roles/knox/common/templates/services/webhdfs/2.4.0/service.xml.j2, roles/knox/gateway/tasks/config.yml
=> knox: fix webhdfs service definition for better support of path parameter

roles/ranger/usersync/tasks/config.yml
=> Ranger Usersync: fix core-site.xml file's owners and permissions modified

roles/spark/common/tasks/hdfs_init.yml, tdp_vars_defaults/spark/spark.yml, tdp_vars_defaults/spark3/spark3.yml
Add default warehouse directory for Sparksql
=> feat(spark):add default warehouse directory for sparksql

roles/knox/common/templates/install.properties.j2
=> fix: path for knox audit log on hdfs

playbooks/ranger_kerberos_install.yml, roles/ranger/admin/tasks/kerberos-spnego-ha.yml, roles/ranger/admin/tasks/kerberos.yml, roles/ranger/common/templates/install.properties.j2, topology.ini
=> feat(spnego): add ha support with kerberos

tdp_vars_defaults/hive/hive.yml
Activate cookie based authentication mechanism for Hiveserver2's http transport mode
=> feat(hive): activate cookie based authentication mechanism

playbooks/meta/all.yml, playbooks/meta/all_per_service.yml, playbooks/meta/hbase.yml, playbooks/meta/hdfs.yml, playbooks/meta/hive.yml, playbooks/meta/kerberos.yml, playbooks/meta/ranger.yml, playbooks/meta/spark.yml, playbooks/meta/spark3.yml, playbooks/meta/yarn.yml
Following #852 a new `kerberos_spnego` was added. Meta playbooks should be updated.
=> feat(meta): update meta playbooks after adding kerberos_spnego component

roles/hive/ranger/tasks/init.yml, tdp_vars_defaults/hive/hive.yml, tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Add parent node in zookeeper for hiveserver2 when using dynamic discovery mode
=> feat(hive): add hiveservers2's namespace in zookeeper

roles/exporter/jmx/tasks/install.yml, roles/hadoop/common/tasks/install.yml, roles/hbase/common/tasks/install_hbase.yml, roles/hbase/common/tasks/install_phoenix.yml, roles/hbase/phoenix/queryserver/common/tasks/install.yml, roles/hbase/ranger/tasks/install.yml, roles/hdfs/ranger/tasks/install.yml, roles/hive/common/tasks/hdfs_init.yml, roles/hive/common/tasks/install_hive.yml, roles/hive/ranger/tasks/install.yml, roles/knox/common/tasks/install.yml, roles/knox/ranger/tasks/install.yml, roles/ranger/admin/tasks/install.yml, roles/ranger/kms/tasks/install.yml, roles/ranger/solr/tasks/install.yml, roles/ranger/usersync/tasks/install.yml, roles/spark/common/tasks/install.yml, roles/yarn/ranger/tasks/install.yml, roles/zookeeper/common/tasks/install.yml
=> fix: ansible.builtin.copy dest should specify full filename

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> refactor(observability): move observability_targets into tdp

roles/ranger/common/tasks/jmx-exporter.yml
=> fix(ranger-jmx-exporter): test that ranger-kms group exists

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat: add unix_group to tdp_observability_target

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> fix(observability): promtail config for hdfs_namenode

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> fix(observability): promtail config for ranger_solr

roles/hive/common/templates/hive-env.sh.j2
=> fix: typo export should be lowercase

roles/spark/common/templates/spark-defaults.conf.j2
=> fix(spark): zero value property not written in spark-defaults.conf

playbooks/meta/all.yml, playbooks/meta/spark3.yml, playbooks/spark3_yarnshuffle_install.yml, roles/spark/yarnshuffle/tasks/install.yml, roles/yarn/nodemanager/tasks/install.yml, tdp_lib_dag/spark3.yml, tdp_vars_defaults/spark3/spark3.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/yarn/yarn.yml, topology.ini
=> spark3: enable dynamic allocation

roles/hbase/common/tasks/jmx-exporter.yml, tdp_vars_defaults/hbase/hbase.yml
=> split hbase and pqs jmx configuration into two files

roles/hbase/phoenix/coprocessor/tasks/install.yml, tdp_vars_defaults/hbase/hbase.yml
Fixes #926
- Change HBase, Phoenix and Phoenix-Queryserver versions.
- Move HBase-Rest server to port 8082 as port 8080 is taken by a process run by zookeeper user.
=> Refactor/hbase 2.5

roles/spark/client/tasks/install.yml, tdp_vars_defaults/spark/spark.yml
Enables spark2 deployment on stack 2.0
=> feat: Enable spark2 on TDPv2

roles/spark/common/templates/log4j2.properties.j2, tdp_vars_defaults/spark3/spark3.yml
Fixes #944 
Same procedure as in PR #945.
=> fix(spark3): hs log4j2 config

roles/hive/common/templates/hive-log4j2.properties.j2, tdp_vars_defaults/hive/hive.yml
Fixes #944 
Same as PR #946. Can also be applied for the tdp stack 1.1 collection since Hive 3.1.3 uses log4j2.
=> fix(hive): hiveserver and metastore log4j2 config

tdp_vars_defaults/hive/hive.yml
Fixes #929
Configuration for Iceberg in Hive:
- Vectorization `hive.vectorized.execution.enabled=false` must be disabled as it is stated in the [Iceberg Documentation](https://iceberg.apache.org/docs/1.4.3/hive/#hadoop-configuration). The parameter `hive.vectorized.execution.enabled` can be changed at runtime.
- Set `tez.mrreader.config.update.properties` variable for projection pruning as stated in the [iceberg documentation](tez.mrreader.config.update.properties=hive.io.file.readcolumn.names,hive.io.file.readcolumn.ids)
=> feat: add configuration for iceberg.

roles/spark/client/tasks/config.yml, roles/spark/client/tasks/install.yml, roles/spark/common/templates/hive-site.xml.j2, tdp_vars_defaults/spark3/spark3.yml
Fixes #929
- Adds iceberg-spark-runtime jar to spark-release/jars directory.
- Configures Spark for Iceberg.
=> feat(iceberg): add iceberg to spark

tdp_vars_defaults/knox/knox.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat(spark3): clarify spark HA configuration

topology.ini
=> feat(knox): put knox in HA mode on master1

roles/ranger/common/templates/ranger-kms-logback.xml.j2
=> variabilize kms-audit log's pattern
